window.fidegresaPageRenderers ??= {};
window.fidegresaPageRenderers.configuracion = ({data, heading, escapeHtml}) => {
  const settings=data.configuracion;
  return `${heading("Configuración","Personaliza cómo funciona tu programa de fidelización")}
    <div class="settings-grid">
      <article class="panel settings-card"><div class="settings-card-heading"><span class="settings-icon">✿</span><div><h2>Marca</h2><p>La identidad que ven tus clientes</p></div></div><div class="settings-line"><div><strong>Nombre del programa</strong><small id="brand-name">${escapeHtml(settings.marca)}</small></div><button class="secondary-button" data-action="edit-brand">Editar</button></div><div class="settings-line"><div><strong>Color de marca</strong><small>Paleta café y crema</small></div><span class="theme-chip selected" style="background:#725037" aria-label="Color café"></span></div></article>
      <article class="panel settings-card"><div class="settings-card-heading"><span class="settings-icon">◐</span><div><h2>Tema</h2><p>Elige cómo se ve tu espacio de trabajo</p></div></div><div class="settings-line"><div><strong>Modo de visualización</strong><small id="theme-description">${settings.tema==="oscuro"?"Tema oscuro":"Tema claro"}</small></div><div class="theme-options"><button class="theme-chip${settings.tema==="claro"?" selected":""}" style="background:#faf8f4" data-action="theme" data-theme="claro" aria-label="Tema claro"></button><button class="theme-chip${settings.tema==="oscuro"?" selected":""}" style="background:#46382e" data-action="theme" data-theme="oscuro" aria-label="Tema oscuro"></button></div></div></article>
      <article class="panel settings-card"><div class="settings-card-heading"><span class="settings-icon">♙</span><div><h2>Mi perfil</h2><p>Tu información de administradora</p></div></div><div class="settings-line"><div><strong>${escapeHtml(settings.perfilNombre)}</strong><small>${escapeHtml(settings.perfilCorreo)}</small></div><button class="secondary-button" data-action="profile">Editar perfil</button></div></article>
      <article class="panel settings-card"><div class="settings-card-heading"><span class="settings-icon">⌂</span><div><h2>Ubicaciones activas</h2><p>Controla dónde está disponible el programa</p></div></div>${data.ubicaciones.map(location=>`<div class="settings-line"><div><strong>${escapeHtml(location.nombre)}</strong><small>${escapeHtml(location.categoria)}</small></div><button class="switch${location.activa?" on":""}" role="switch" aria-checked="${location.activa}" aria-label="Cambiar estado de ${escapeHtml(location.nombre)}" data-action="toggle-location" data-id="${location.id}"></button></div>`).join("")}<button class="text-button" data-page="ubicaciones">Administrar ubicaciones →</button></article>
      <article class="panel settings-card wide"><div class="settings-card-heading"><span class="settings-icon">ⓘ</span><div><h2>Cuenta</h2><p>Administra los datos guardados en este dispositivo</p></div></div><div class="settings-line"><div><strong>Eliminar cuenta</strong><small>Elimina los cambios y restaura los datos de demostración de este navegador.</small></div><button class="danger-button" data-action="delete-account">Eliminar cuenta</button></div></article>
    </div>`;
};
