window.fidegresaPageRenderers ??= {};
window.fidegresaPageRenderers.geolocalizacion = ({data, heading, escapeHtml, initials}) => {
  const geo=data.geolocalizacion;
  const location=data.ubicaciones.find(place=>Number(place.id)===Number(geo.ubicacionId))||data.ubicaciones[0];
  const nearby=data.clientes.slice(0,4);
  return `${heading("Tu comunidad, cerca","Visualiza clientes alrededor de tus ubicaciones. La ubicación de las personas es ilustrativa.")}
    <div class="geo-layout"><article class="panel map-panel"><div class="map-canvas" role="img" aria-label="Mapa esquemático con radio de ${geo.radio} metros alrededor de ${escapeHtml(location?.nombre||"la ubicación")}"><span class="map-water"></span><span class="map-label" style="top:14%;left:12%">CENTRO</span><span class="map-label" style="top:76%;left:69%">PARQUE CENTRAL</span><span class="map-label" style="top:20%;left:72%">SAN MIGUEL</span><span class="map-road one"></span><span class="map-road two"></span><div class="map-radius"><span class="map-radius-label">${geo.radio} m</span></div><span class="map-shop">⌂</span>${nearby.map((person,index)=>`<span class="map-pin p${index+1}"><span>${escapeHtml(person.iniciales||initials(person.nombre))}</span></span>`).join("")}<div class="map-toolbar"><button class="secondary-button" data-action="center-map">◎ &nbsp; Centrar mapa</button></div><span class="map-credit">Mapa esquemático · Ubicaciones de demostración</span></div></article>
      <article class="panel geo-settings"><h2>Alcance de tu ubicación</h2><p>Define el radio de alcance para ver cuántos clientes están cerca de tu negocio.</p><label for="radius-input">Ubicación del negocio</label><select id="geo-location" class="form-control">${data.ubicaciones.map(place=>`<option value="${place.id}"${Number(place.id)===Number(geo.ubicacionId)?" selected":""}>${escapeHtml(place.nombre)}</option>`).join("")}</select><div class="range-value"><strong id="radius-value">${geo.radio} m</strong><span>Radio máximo: 1 km</span></div><input id="radius-input" class="range-input" type="range" min="100" max="1000" step="50" value="${geo.radio}" aria-label="Radio de alcance en metros"><div class="range-labels"><span>100 m</span><span>500 m</span><span>1.000 m</span></div><div class="nearby-list"><strong class="panel-title">Clientes cercanos</strong>${nearby.map((person,index)=>`<div class="nearby-row"><span class="customer-avatar">${escapeHtml(person.iniciales||initials(person.nombre))}</span><div><strong>${escapeHtml(person.nombre)}</strong><small>${escapeHtml(person.tarjeta)}</small></div><span class="distance">${[120,280,460,720][index]} m</span></div>`).join("")}</div><div class="geo-note"><span>ⓘ</span><span><b>Privacidad primero.</b> Los puntos del mapa son ilustrativos; esta demostración no solicita ni rastrea la ubicación real de los clientes.</span></div></article></div>`;
};
